//! Adversarial efficacy: drive the *real* `sng_swg::YaraEngine` and
//! Suricata over corpora built specifically to **evade** signature
//! detection, and report them as their own rows in the efficacy matrix
//! (`malware_adversarial`, `ips_adversarial`).
//!
//! Where [`crate::malware`] and [`crate::ips`] measure detection of the
//! canonical, cleanly-framed attack shapes, this module measures
//! detection of the obfuscation / evasion shapes a motivated attacker
//! reaches for:
//!
//! * **malware_adversarial** — UPX-packed executables, archive-smuggled
//!   / double-extension droppers, HTML smuggling (base64 -> Blob ->
//!   download), polyglot PDF + auto-exec JavaScript, obfuscated VBA macro
//!   source, encoded / download-cradle PowerShell, and eval-equivalent
//!   JavaScript (`Function`/`setTimeout`/indirect `eval` over
//!   `atob`/`unescape`). Driven through the real
//!   `YaraEngine::with_builtin_rules` scan path.
//!
//! * **ips_adversarial** — fragmented HTTP, session-spliced TCP,
//!   double-encoded URIs and DoH tunneling, replayed through the real
//!   Suricata binary (defrag + stream reassembly + normalisation) using
//!   SNG's `ConfigGenerator`-rendered `suricata.yaml`.
//!
//! Every sample is a benign synthetic stand-in (EICAR markers, minimal
//! valid headers, inert payloads); no live malware is used. The fixtures
//! are committed and regenerated by the `gen_samples.py` /
//! `gen_adversarial_pcaps.py` scripts next to them.

use std::path::PathBuf;

use serde::Deserialize;
use sng_swg::{YaraEngine, YaraSeverity};

use crate::ips::{alerts_for_pcap, render_config, suricata_available, WorkDirGuard};
use crate::report::{Case, Feature, FunctionReport, Kind, Targets};

// ===== malware_adversarial =============================================

fn malware_fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/malware/adversarial")
}

/// One entry of the committed `manifest.json`: a fixture file, whether
/// it is known-bad, the malware family it represents, and a human label.
#[derive(Debug, Deserialize)]
struct ManifestEntry {
    file: String,
    bad: bool,
    #[allow(dead_code)]
    family: String,
    desc: String,
}

/// Drive the real `YaraEngine` over the adversarial malware corpus.
pub async fn run_malware() -> FunctionReport {
    let engine = match YaraEngine::with_builtin_rules() {
        Ok(e) => e,
        Err(e) => {
            return FunctionReport::untested(
                "malware_adversarial",
                "sng-swg",
                Kind::Detection,
                &format!("YARA built-in rules failed to compile: {e}"),
            );
        }
    };

    let dir = malware_fixtures_dir();
    let manifest_path = dir.join("manifest.json");
    let manifest_text = match std::fs::read_to_string(&manifest_path) {
        Ok(t) => t,
        Err(e) => {
            return FunctionReport::untested(
                "malware_adversarial",
                "sng-swg",
                Kind::Detection,
                &format!(
                    "adversarial malware manifest missing ({}): {e}",
                    manifest_path.display()
                ),
            );
        }
    };
    let manifest: Vec<ManifestEntry> = match serde_json::from_str(&manifest_text) {
        Ok(m) => m,
        Err(e) => {
            return FunctionReport::untested(
                "malware_adversarial",
                "sng-swg",
                Kind::Detection,
                &format!("could not parse adversarial malware manifest: {e}"),
            );
        }
    };

    let mut cases = Vec::new();
    for entry in &manifest {
        let path = dir.join(&entry.file);
        let content = match std::fs::read(&path) {
            Ok(c) => c,
            Err(e) => {
                return FunctionReport::untested(
                    "malware_adversarial",
                    "sng-swg",
                    Kind::Detection,
                    &format!("could not read adversarial sample {}: {e}", path.display()),
                );
            }
        };
        let matches = engine.scan(&content);
        let detected = !matches.is_empty();
        let actual = if detected {
            let worst = matches
                .iter()
                .map(|m| m.severity)
                .max()
                .unwrap_or(YaraSeverity::Suspicious);
            format!("detect ({})", worst.as_str())
        } else {
            "pass".to_string()
        };
        let correct = if entry.bad { detected } else { !detected };
        cases.push(Case {
            description: entry.desc.clone(),
            bad: entry.bad,
            expected: if entry.bad { "detect" } else { "pass" }.into(),
            actual,
            correct,
        });
    }

    FunctionReport::from_cases(
        "malware_adversarial",
        "sng-swg",
        Kind::Detection,
        Targets::default(),
        cases,
        Some(
            "Real YaraEngine::scan over an evasion-focused corpus (UPX packing, \
             archive smuggling / double extensions, HTML smuggling, polyglot PDF+JS, \
             obfuscated VBA, encoded PowerShell, eval-equivalent JS). Benign \
             look-alikes (base64 data-URI pages, admin scripts, macro-free docs, \
             clean PDFs/ZIPs) pass clean to bound the false-positive rate."
                .into(),
        ),
    )
    .with_features(vec![
        Feature {
            name: "Evasion-shape signature coverage".into(),
            how: "yara-x built-in rules extended with packer, archive-smuggling, \
                  HTML-smuggling, PDF-JS, VBA-obfuscation, encoded-PowerShell and \
                  eval-equivalent-JS signatures; scan() runs them over file bytes."
                .into(),
            coverage: "UPX, double-extension ZIP, base64 Blob HTML, polyglot PDF+JS, \
                       Chr()-built VBA, -EncodedCommand PowerShell, Function(atob())"
                .into(),
        },
        Feature {
            name: "Archive name inspection without unpacking".into(),
            how: "matches the plaintext ZIP local-file-header filename so a deflated \
                  payload's dangerous / double extension is caught without decompression."
                .into(),
            coverage: "invoice.pdf.exe, *.scr/*.hta/*.vbe inside ZIP".into(),
        },
    ])
}

// ===== ips_adversarial =================================================

fn ips_adversarial_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/ips/adversarial")
}

/// A replayed adversarial PCAP and whether it must alert.
struct PcapCase {
    file: &'static str,
    bad: bool,
    desc: &'static str,
}

fn ips_corpus() -> Vec<PcapCase> {
    vec![
        // --- known-bad: MUST alert (after defrag / stream reassembly /
        //     evasion-aware match) ---
        PcapCase {
            file: "bad-frag-http-traversal.pcap",
            bad: true,
            desc: "fragmented HTTP directory traversal (/etc/passwd across IP fragments)",
        },
        PcapCase {
            file: "bad-frag-eicar-download.pcap",
            bad: true,
            desc: "fragmented EICAR download (reassembled by defrag engine)",
        },
        PcapCase {
            file: "bad-splice-tcp-sqli.pcap",
            bad: true,
            desc: "session-spliced SQLi UNION SELECT (one byte per TCP segment)",
        },
        PcapCase {
            file: "bad-splice-tcp-traversal.pcap",
            bad: true,
            desc: "session-spliced directory traversal (stream reassembly)",
        },
        PcapCase {
            file: "bad-double-encoded-traversal.pcap",
            bad: true,
            desc: "double-encoded path traversal (%252e%252e%252f)",
        },
        PcapCase {
            file: "bad-double-encoded-xss.pcap",
            bad: true,
            desc: "double-encoded reflected XSS (%253Cscript)",
        },
        PcapCase {
            file: "bad-doh-tunnel-post.pcap",
            bad: true,
            desc: "DoH tunneling POST /dns-query (application/dns-message)",
        },
        PcapCase {
            file: "bad-doh-tunnel-get.pcap",
            bad: true,
            desc: "DoH tunneling GET /dns-query?dns=<base64url>",
        },
        // --- known-good: same evasion transport, benign content ---
        PcapCase {
            file: "good-frag-http-benign.pcap",
            bad: false,
            desc: "benign fragmented HTTP GET /index.html",
        },
        PcapCase {
            file: "good-splice-tcp-benign.pcap",
            bad: false,
            desc: "benign session-spliced HTTP GET /home",
        },
        PcapCase {
            file: "good-single-encoded-uri.pcap",
            bad: false,
            desc: "benign singly-encoded URI (%2e, not double-encoded)",
        },
        PcapCase {
            file: "good-api-json-query.pcap",
            bad: false,
            desc: "benign JSON API POST /api/query (DoH look-alike path)",
        },
        PcapCase {
            file: "good-dns-udp-normal.pcap",
            bad: false,
            desc: "benign plain DNS over UDP/53",
        },
        PcapCase {
            file: "good-dns-info-page.pcap",
            bad: false,
            desc: "benign HTTP GET /support/dns-info.html (substring only)",
        },
    ]
}

/// Drive the real Suricata binary over the adversarial IPS corpus.
pub async fn run_ips() -> FunctionReport {
    let version = match suricata_available().await {
        Some(v) => v,
        None => {
            return FunctionReport::untested(
                "ips_adversarial",
                "sng-ips",
                Kind::Detection,
                "suricata binary not found on PATH; install Suricata to measure IPS detection efficacy",
            );
        }
    };

    let fixtures = ips_adversarial_dir();
    let rules = fixtures.join("adversarial.rules");
    if !rules.exists() {
        return FunctionReport::untested(
            "ips_adversarial",
            "sng-ips",
            Kind::Detection,
            "adversarial IPS fixtures missing (expected bench/efficacy/fixtures/ips/adversarial)",
        );
    }

    let work = std::env::temp_dir().join(format!("sng-efficacy-ips-adv-{}", std::process::id()));
    if let Err(e) = tokio::fs::create_dir_all(&work).await {
        return FunctionReport::untested(
            "ips_adversarial",
            "sng-ips",
            Kind::Detection,
            &format!("could not create IPS work dir {}: {e}", work.display()),
        );
    }
    let _work_guard = WorkDirGuard(work.clone());
    let eve = work.join("eve.json");
    let stats_sock = work.join("suricata-command.socket");
    let yaml_path = work.join("suricata.yaml");

    let yaml = match render_config(&rules, &eve, &stats_sock) {
        Ok(y) => y,
        Err(e) => {
            return FunctionReport::untested("ips_adversarial", "sng-ips", Kind::Detection, &e)
        }
    };
    if let Err(e) = tokio::fs::write(&yaml_path, &yaml).await {
        return FunctionReport::untested(
            "ips_adversarial",
            "sng-ips",
            Kind::Detection,
            &format!("could not write rendered suricata.yaml: {e}"),
        );
    }

    let mut cases = Vec::new();
    for c in ips_corpus() {
        let pcap = fixtures.join(c.file);
        let n = match alerts_for_pcap(&yaml_path, &pcap, &work, &eve).await {
            Ok(n) => n,
            Err(e) => {
                return FunctionReport::untested(
                    "ips_adversarial",
                    "sng-ips",
                    Kind::Detection,
                    &format!("suricata execution failed on {}: {e}", c.file),
                );
            }
        };
        let alerted = n > 0;
        let correct = if c.bad { alerted } else { !alerted };
        cases.push(Case {
            description: c.desc.into(),
            bad: c.bad,
            expected: if c.bad { "detect" } else { "no-alert" }.into(),
            actual: format!("{n} alert(s)"),
            correct,
        });
    }

    FunctionReport::from_cases(
        "ips_adversarial",
        "sng-ips",
        Kind::Detection,
        Targets::default(),
        cases,
        Some(format!(
            "Real {version} driven by SNG's ConfigGenerator-rendered suricata.yaml over \
             an evasion corpus: fragmented HTTP and session-spliced TCP (caught after \
             defrag + stream reassembly), double-encoded URIs and DoH tunneling (caught \
             by evasion-aware signatures). EVE alerts normalised through \
             sng_ips::EveAlert::to_ips_event; offline PCAP replay in IDS mode."
        )),
    )
    .with_features(vec![
        Feature {
            name: "Reassembly-resilient detection".into(),
            how: "Suricata defrag + TCP stream reassembly rebuild the payload before the \
                  content match, so a pattern split across IP fragments or one-byte \
                  segments is still caught."
                .into(),
            coverage: "fragmented HTTP, session-spliced SQLi / traversal".into(),
        },
        Feature {
            name: "Evasion-aware signatures".into(),
            how: "rules match the double-percent-encoded bytes and the DoH wire markers \
                  directly, catching evasions that survive a single decode pass."
                .into(),
            coverage: "double-encoded ../ and <script>, DoH dns-message / dns-query".into(),
        },
    ])
}
