-- Code generated by `sng-migrate squash` on 2026-06-09T10:30:51Z. DO NOT EDIT BY HAND.
-- Consolidated down baseline of migrations 001..041.
--
-- This baseline is for NEW deployments only. A fresh database applies
-- it once instead of replaying every individual migration; it must be
-- recorded as schema version 41 so that migration 042 and later apply
-- on top unchanged. EXISTING deployments must keep applying the
-- individual migration files and must NOT run this baseline.
-- Regenerate with `sng-migrate squash`; see docs/migration-consolidation.md.

-- ===========================================================================
-- 041_devices_pubkey_unique.down.sql
-- ===========================================================================
-- Migration 041 (down): drop the per-tenant device public-key unique
-- index. Reverts to allowing duplicate Ed25519 keys within a tenant.
DROP INDEX IF EXISTS uq_devices_tenant_public_key;

-- ===========================================================================
-- 040_metering.down.sql
-- ===========================================================================
-- Reverse migration for cost metering & budget guardrails (down).
-- Dropping each table removes its RLS policy, indexes, and trigger
-- implicitly.
DROP TRIGGER IF EXISTS tenant_budgets_set_updated_at ON tenant_budgets;
DROP POLICY IF EXISTS tenant_budgets_tenant_isolation ON tenant_budgets;
DROP TABLE IF EXISTS tenant_budgets;

DROP TRIGGER IF EXISTS tenant_usage_set_updated_at ON tenant_usage;
DROP POLICY IF EXISTS tenant_usage_tenant_isolation ON tenant_usage;
DROP TABLE IF EXISTS tenant_usage;

-- ===========================================================================
-- 039_compliance_evidence.down.sql
-- ===========================================================================
-- Reverse migration for SOC2 compliance evidence (down).
-- Dropping the table removes its indexes and constraints implicitly.
DROP TABLE IF EXISTS compliance_evidence;

-- ===========================================================================
-- 038_pops.down.sql
-- ===========================================================================
-- Migration 038 (down): drop the cloud-PoP tables. Dropping each
-- table removes its RLS policies, indexes, and triggers implicitly.
-- Drop in FK-dependency order: the two tables that reference pops
-- first, then pops itself.

DROP TABLE IF EXISTS tenant_pop_assignments;
DROP TABLE IF EXISTS pop_health;
DROP TABLE IF EXISTS pops;

-- ===========================================================================
-- 037_inline_casb.down.sql
-- ===========================================================================
-- Reverse migration for inline CASB (down).
-- Dropping the table removes its RLS policy, indexes, and trigger
-- implicitly.
DROP TRIGGER IF EXISTS inline_casb_rules_set_updated_at ON inline_casb_rules;
DROP POLICY IF EXISTS inline_casb_rules_tenant_isolation ON inline_casb_rules;
DROP TABLE IF EXISTS inline_casb_rules;

-- ===========================================================================
-- 036_sdwan_sla.down.sql
-- ===========================================================================
-- Migration 036 (down): drop the sdwan_sla_policies table and its
-- policies. Dropping the table removes its RLS policies and indexes
-- implicitly.

DROP TABLE IF EXISTS sdwan_sla_policies;

-- ===========================================================================
-- 035_site_ha.down.sql
-- ===========================================================================
-- 035_site_ha — down migration.
--
-- Drop the partial index first: it references ha_peer_device_id,
-- the column we are about to remove.
DROP INDEX IF EXISTS sites_ha_peer_device_idx;

ALTER TABLE sites DROP COLUMN IF EXISTS ha_peer_device_id;
ALTER TABLE sites DROP COLUMN IF EXISTS ha_mode;

-- ===========================================================================
-- 034_idp_configs.down.sql
-- ===========================================================================
-- Migration 034 (down): drop the idp_configs table and its policies.
-- Dropping the table removes its RLS policies and indexes implicitly.

DROP TABLE IF EXISTS idp_configs;

-- ===========================================================================
-- 033_troubleshoot_sessions.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS troubleshoot_sessions;

-- ===========================================================================
-- 032_kb_entries.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS kb_entries;

-- ===========================================================================
-- 031_ops_health.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS ops_health_snapshots;

-- ===========================================================================
-- 030_scheduled_reviews.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS policy_review_schedules;

-- ===========================================================================
-- 029_ai_correlations.down.sql
-- ===========================================================================
-- Migration 029 down: drop AI alert correlations table.
DROP TABLE IF EXISTS ai_alert_correlations;

-- ===========================================================================
-- 028_reserved.down.sql
-- ===========================================================================
-- reserved for future use

-- ===========================================================================
-- 027_reserved.down.sql
-- ===========================================================================
-- reserved for future use

-- ===========================================================================
-- 026_ai_suggestions.down.sql
-- ===========================================================================
DROP POLICY IF EXISTS tenant_isolation ON ai_policy_suggestions;
DROP TABLE IF EXISTS ai_policy_suggestions;

-- ===========================================================================
-- 025_playbook_approvals.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS playbook_approvals;

-- ===========================================================================
-- 024_playbook_executions.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS playbook_step_results;
DROP TABLE IF EXISTS playbook_executions;

-- ===========================================================================
-- 023_playbooks.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS playbooks;

-- ===========================================================================
-- 022_compliance.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS compliance_reports;

-- ===========================================================================
-- 021_device_enrollment.down.sql
-- ===========================================================================
-- Rollback migration 019: Device enrollment tables.
DROP TABLE IF EXISTS device_certificates;
DROP TABLE IF EXISTS device_enrollments;
DROP TYPE IF EXISTS device_enrollment_status;

-- ===========================================================================
-- 020_scim_external_ids.down.sql
-- ===========================================================================
-- Rollback migration 018: SCIM external IDs.

DROP INDEX IF EXISTS idx_roles_tenant_external_id;
ALTER TABLE roles DROP COLUMN IF EXISTS external_id;

DROP INDEX IF EXISTS idx_users_tenant_external_id;

-- ===========================================================================
-- 019_data_classification.down.sql
-- ===========================================================================
DROP POLICY IF EXISTS data_classifications_tenant_isolation ON data_classifications;
DROP TABLE IF EXISTS data_classifications;

-- ===========================================================================
-- 018_browser_policies.down.sql
-- ===========================================================================
DROP POLICY IF EXISTS browser_policies_tenant_isolation ON browser_policies;
DROP TABLE IF EXISTS browser_policies;

-- ===========================================================================
-- 017_dlp.down.sql
-- ===========================================================================
-- Reverse migration for DLP tables (Phase 4).
DROP POLICY IF EXISTS dlp_matches_tenant_isolation ON dlp_matches;
DROP TABLE IF EXISTS dlp_matches;

DROP POLICY IF EXISTS dlp_fingerprints_tenant_isolation ON dlp_fingerprints;
DROP TABLE IF EXISTS dlp_fingerprints;

DROP TRIGGER IF EXISTS dlp_policies_set_updated_at ON dlp_policies;
DROP POLICY IF EXISTS dlp_policies_tenant_isolation ON dlp_policies;
DROP TABLE IF EXISTS dlp_policies;

-- ===========================================================================
-- 016_casb.down.sql
-- ===========================================================================
DROP TABLE IF EXISTS casb_posture_checks;
DROP TABLE IF EXISTS casb_discovered_apps;
DROP TABLE IF EXISTS casb_connectors;

-- ===========================================================================
-- 015_msps.down.sql
-- ===========================================================================
-- Rollback for 015_msps.up.sql.
--
-- Order matters: drop the FK column on tenants first so msps can
-- be dropped without violating the ON DELETE SET NULL contract,
-- then the join table, then the top-level table.
DROP INDEX IF EXISTS tenants_msp_idx;
ALTER TABLE tenants DROP COLUMN IF EXISTS msp_id;
DROP TABLE IF EXISTS msp_tenants;
DROP TABLE IF EXISTS msps;

-- ===========================================================================
-- 014_integrations.down.sql
-- ===========================================================================
-- Rollback for 014_integrations.up.sql.
DROP TABLE IF EXISTS integration_deliveries;
DROP TABLE IF EXISTS integration_connectors;

-- ===========================================================================
-- 013_alerts.down.sql
-- ===========================================================================
-- 013_alerts (DOWN) — drop alerts + suppressions + feedback.
--
-- Drop in reverse FK order: alert_feedback and the suppression
-- FK on alerts must go before the referenced tables.

DROP POLICY IF EXISTS alert_feedback_tenant_isolation     ON alert_feedback;
DROP POLICY IF EXISTS alert_suppressions_tenant_isolation ON alert_suppressions;
DROP POLICY IF EXISTS alerts_tenant_isolation             ON alerts;

DROP INDEX IF EXISTS alert_feedback_dimension_idx;
DROP INDEX IF EXISTS alert_suppressions_dimension_idx;
DROP INDEX IF EXISTS alert_suppressions_kind_idx;
DROP INDEX IF EXISTS alerts_dimension_idx;
DROP INDEX IF EXISTS alerts_open_idx;
DROP INDEX IF EXISTS alerts_list_idx;

DROP TABLE IF EXISTS alert_feedback;
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS alert_suppressions;

-- ===========================================================================
-- 012_baseline_models.down.sql
-- ===========================================================================
-- 012_baseline_models (DOWN) — drop the baseline state.
--
-- Tables are dropped after the policies / indexes; the indexes
-- are auto-dropped with the table but we drop them explicitly
-- so the down migration is symmetrical with the up.

DROP POLICY IF EXISTS baseline_models_tenant_isolation ON baseline_models;
DROP INDEX IF EXISTS baseline_models_recent_idx;
DROP TABLE IF EXISTS baseline_models;

-- ===========================================================================
-- 011_policy_graphs_is_draft.down.sql
-- ===========================================================================
-- 011_policy_graphs_is_draft — down migration.
--
-- Dropping the index first matters because the partial-index
-- predicate references the column we're about to remove.
DROP INDEX IF EXISTS policy_graphs_tenant_version_live_idx;
ALTER TABLE policy_graphs DROP COLUMN IF EXISTS is_draft;

-- ===========================================================================
-- 010_policy_rollouts.down.sql
-- ===========================================================================
-- 010_policy_rollouts (DOWN) — drop the rollout state machine.
--
-- Order matters: triggers + policies must be dropped before the
-- function / table; the function itself is independent of the
-- table so we drop it after the trigger.

DROP TRIGGER IF EXISTS policy_rollouts_stage_transition ON policy_rollouts;
DROP FUNCTION IF EXISTS policy_rollouts_check_transition();
DROP POLICY IF EXISTS policy_rollouts_tenant_isolation ON policy_rollouts;
DROP INDEX IF EXISTS policy_rollouts_graph_idx;
DROP INDEX IF EXISTS policy_rollouts_list_idx;
DROP INDEX IF EXISTS policy_rollouts_active_idx;
DROP TABLE IF EXISTS policy_rollouts;

-- ===========================================================================
-- 009_app_registry_seed.down.sql
-- ===========================================================================
-- 009_app_registry_seed — rollback.
--
-- Removes only the rows the seed migration inserted. Operator-added
-- rows (is_system = FALSE) are preserved so a down/up cycle does
-- not destroy operator data.

DELETE FROM app_registry WHERE is_system = TRUE;

-- ===========================================================================
-- 008_app_registry.down.sql
-- ===========================================================================
-- 008_app_registry — rollback.

DROP TABLE IF EXISTS app_registry_overrides;
DROP TABLE IF EXISTS app_registry;

-- ===========================================================================
-- 007_policy_bundle_sha256.down.sql
-- ===========================================================================
-- 007_policy_bundle_sha256 — rollback
--
-- Drops the precomputed digest column. The HEAD / If-None-Match
-- path will fall back to recomputing the digest in Go from the
-- bundle bytes (the pre-migration behaviour).

ALTER TABLE policy_bundles
    DROP CONSTRAINT IF EXISTS policy_bundles_sha256_length_chk;

ALTER TABLE policy_bundles
    DROP COLUMN IF EXISTS sha256;

-- ===========================================================================
-- 006_tenant_api_keys.down.sql
-- ===========================================================================
DROP POLICY IF EXISTS tenant_api_keys_tenant_isolation ON tenant_api_keys;
DROP INDEX IF EXISTS tenant_api_keys_tenant_created_idx;
DROP INDEX IF EXISTS tenant_api_keys_hash_idx;
DROP TABLE IF EXISTS tenant_api_keys;

-- ===========================================================================
-- 005_policy_signing_keys.down.sql
-- ===========================================================================
ALTER TABLE policy_bundles DROP COLUMN IF EXISTS key_id;

DROP POLICY IF EXISTS policy_signing_keys_tenant_isolation ON policy_signing_keys;
DROP INDEX IF EXISTS policy_signing_keys_tenant_one_active_idx;
DROP INDEX IF EXISTS policy_signing_keys_tenant_active_idx;
DROP TABLE IF EXISTS policy_signing_keys;

-- ===========================================================================
-- 004_webhook_processing.down.sql
-- ===========================================================================
-- ShieldNet Gateway (SNG) — revert webhook delivery atomic-claim migration.
--
-- Reverting means narrowing the CHECK back to four states. Any
-- rows in 'processing' state at the time of the down-migration are
-- reset to 'pending' so the constraint can be re-tightened without
-- violating it; their next_retry_at is left as-is so the legacy
-- (non-atomic) ListPending will pick them up again. The legacy
-- duplicate-delivery hazard returns under this revert — the
-- migration was added precisely to fix it.

DROP INDEX IF EXISTS idx_webhook_deliveries_claimable;

UPDATE webhook_deliveries
    SET status = 'pending'
    WHERE status = 'processing';

ALTER TABLE webhook_deliveries
    DROP CONSTRAINT IF EXISTS webhook_deliveries_status_check;

ALTER TABLE webhook_deliveries
    ADD CONSTRAINT webhook_deliveries_status_check
        CHECK (status IN ('pending', 'delivered', 'failed', 'exhausted'));

CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_pending_next
    ON webhook_deliveries (status, next_retry_at)
    WHERE status = 'pending';

-- ===========================================================================
-- 003_webhooks.down.sql
-- ===========================================================================
-- ShieldNet Gateway (SNG) — drop webhook tables.

DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhook_endpoints;

-- ===========================================================================
-- 002_role_bootstrap.down.sql
-- ===========================================================================
-- Down-migration for 002_role_bootstrap.
--
-- Mirror image of the up migration: revoke every privilege we
-- granted, in the same order (default privileges first, then the
-- concrete grants on existing objects). The role itself is left
-- in place — role lifecycle is an operator concern, not a schema
-- concern (see docs/deploy.md and the head comment in
-- 002_role_bootstrap.up.sql).
--
-- Robust against an out-of-band role drop. PostgreSQL raises
-- `ERROR: role "sng_app" does not exist` when REVOKE / ALTER
-- DEFAULT PRIVILEGES target a non-existent role; without the
-- DO-block guard below, dropping `sng_app` before running the
-- down migration would fail the entire migration and leave the
-- migration tracker in a dirty state. The guard makes the down
-- path truly idempotent: if the role is gone, the privileges
-- already cannot be exercised by anyone, so revoking them is a
-- no-op that we can skip.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sng_app') THEN
        -- Revoke default privileges first so they don't get re-applied
        -- on new objects created between the REVOKE on existing tables
        -- and the next migration.
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public
                    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM sng_app';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public
                    REVOKE USAGE ON SEQUENCES FROM sng_app';

        EXECUTE 'REVOKE USAGE ON ALL SEQUENCES IN SCHEMA public FROM sng_app';
        EXECUTE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM sng_app';
        EXECUTE 'REVOKE USAGE ON SCHEMA public FROM sng_app';
    END IF;
END $$;

-- ===========================================================================
-- 001_initial_schema.down.sql
-- ===========================================================================
-- Down-migration for 001_initial_schema. Drops every object in
-- reverse dependency order so re-running `up` lands cleanly.

DROP TABLE IF EXISTS policy_bundles;
DROP TABLE IF EXISTS policy_graphs;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS claim_tokens;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS sites;
DROP TABLE IF EXISTS tenants;

DROP FUNCTION IF EXISTS sng_set_updated_at();

