-- 059_reserved_slot_placeholder
--
-- Backfill of the skipped migration slot 059. The 059–062 range was
-- carved up across parallel feature branches; 060 (dlp_review_queue),
-- 061 (casb_app_classification), and 062 (policy_templates) all landed
-- on main, but slot 059 was reserved by a sibling branch that never
-- delivered. The resulting hole (058 -> 060) makes the migration set
-- non-contiguous, which the structural guard rejects:
--
--   * sng-migrate check-versions  ->  "gap in migration sequence:
--     060 follows 058 (expected 059)"
--   * internal/migrate TestCheckVersionSequence_EmbeddedSource and
--     TestSourceFS_Pairs fail on the same gap.
--
-- golang-migrate applies versions in increasing order and never
-- retroactively fills a lower version once a database is past it, so
-- the gap cannot be safely left for a later 059 to backfill against an
-- already-migrated database — the slot has to be occupied now.
--
-- This migration intentionally makes no schema change: it only claims
-- version 059 so the sequence is gap-free. The statement below is a
-- deliberate no-op (a valid, executable statement so golang-migrate
-- does not treat the body as an empty query) and is trivially
-- idempotent and reversible.
SELECT 1;
