//! Cross-language contract test: a signed IPS rule bundle produced by
//! the Go control plane (`internal/service/threatintel`) must verify,
//! decode, and classify identically on the Rust edge.
//!
//! The fixture `testdata/go_ips_bundle.json` is generated by the Go
//! producer over a fixed Ed25519 seed and a fixed IOC set (one JA3,
//! domain, IP and CIDR with attribution). It carries the envelope, the
//! signing public key, and the per-category rule counts the Go
//! classifier computed. This test independently:
//!   1. installs the public key in an `IpsRuleVerifier`,
//!   2. reconstructs the wire `IpsRuleBundle` from the base64 envelope,
//!   3. `verify_and_decode`s it (proving Go's `crypto/ed25519` +
//!      `msgpack/v5` bytes verify under `ed25519-dalek` + `rmp_serde`),
//!   4. re-classifies the decoded rules with `rule_stats` and asserts
//!      the counts match the Go side byte-for-byte.
//!
//! A drift in the wire format, the signing-key-id derivation, or the
//! classifier on either side fails this test.

// `.expect("fixture")` / `.unwrap()` are idiomatic in test
// scaffolding; integration test files are separate crates so the
// crate-level allow list is repeated here.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use base64::Engine as _;
use serde::Deserialize;

use sng_ips::rules::{IpsRuleSignature, IpsSigningKeyId};
use sng_ips::{IpsRuleBundle, IpsRuleVerifier, RuleCategory, RuleSource, rule_stats};

#[derive(Deserialize)]
struct Envelope {
    alg: String,
    signing_key_id: String,
    body: String,
    signature: String,
}

#[derive(Deserialize)]
struct Fixture {
    envelope: Envelope,
    public_key_hex: String,
    signing_key_id: String,
    version: u64,
    rules_text: String,
    by_category: std::collections::BTreeMap<String, usize>,
    total: usize,
}

fn load_fixture() -> Fixture {
    let raw = include_str!("../testdata/go_ips_bundle.json");
    serde_json::from_str(raw).expect("fixture parses")
}

fn b64(s: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(s)
        .expect("valid base64")
}

#[test]
fn go_bundle_verifies_and_decodes_on_edge() {
    let fx = load_fixture();
    assert_eq!(fx.envelope.alg, "ed25519");
    // The Go producer derives the signing key id from the public key;
    // the envelope and the fixture's own derivation must agree.
    assert_eq!(fx.envelope.signing_key_id, fx.signing_key_id);

    // Trust store: pin the Go signer's public key under its id.
    let pk_bytes: [u8; 32] = hex::decode(&fx.public_key_hex)
        .expect("hex pubkey")
        .try_into()
        .expect("32-byte pubkey");
    let key_id = IpsSigningKeyId::new(fx.signing_key_id.clone()).expect("valid key id");
    let mut verifier = IpsRuleVerifier::new();
    verifier
        .add_key(key_id.clone(), &pk_bytes)
        .expect("add key");

    // Reconstruct the wire bundle from the base64 envelope.
    let body = b64(&fx.envelope.body);
    let sig_bytes: [u8; 64] = b64(&fx.envelope.signature)
        .try_into()
        .expect("64-byte signature");
    let bundle = IpsRuleBundle {
        body,
        signature: IpsRuleSignature { bytes: sig_bytes },
        signing_key_id: key_id,
    };

    let claims = verifier
        .verify_and_decode(&bundle)
        .expect("Go-signed bundle verifies and decodes on the edge");

    assert_eq!(claims.schema_version, 1);
    assert_eq!(claims.version, fx.version);
    assert_eq!(claims.source, RuleSource::CustomOrg);
    assert_eq!(claims.rules_text, fx.rules_text);

    // Independent edge re-classification must match the Go counts.
    let stats = rule_stats(&claims.rules_text);
    assert_eq!(stats.total, fx.total, "total rule count mismatch");
    for cat in RuleCategory::all() {
        let want = fx.by_category.get(cat.as_str()).copied().unwrap_or(0);
        assert_eq!(
            stats.count(cat),
            want,
            "category {} count: edge {} vs go {}",
            cat.as_str(),
            stats.count(cat),
            want
        );
    }
}

#[test]
fn go_bundle_rejected_under_wrong_key() {
    let fx = load_fixture();
    let body = b64(&fx.envelope.body);
    let sig_bytes: [u8; 64] = b64(&fx.envelope.signature).try_into().unwrap();
    let key_id = IpsSigningKeyId::new(fx.signing_key_id.clone()).unwrap();
    let bundle = IpsRuleBundle {
        body,
        signature: IpsRuleSignature { bytes: sig_bytes },
        signing_key_id: key_id.clone(),
    };

    // A different (non-pinned) key under the same id must fail verify.
    let mut wrong = IpsRuleVerifier::new();
    let other = [7u8; 32];
    // [7;32] may or may not be a valid point; if it is, verification
    // still fails on the signature. Skip if the bytes aren't a point.
    if wrong.add_key(key_id, &other).is_ok() {
        assert!(wrong.verify_and_decode(&bundle).is_err());
    }
}
