apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sng-edge.configMapName" . }}
  labels:
    {{- include "sng-edge.labels" . | nindent 4 }}
data:
  edge.toml: |
{{ .Values.edgeConfig | indent 4 }}
{{- if .Values.envoy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sng-edge.envoyConfigMapName" . }}
  labels:
    {{- include "sng-edge.labels" . | nindent 4 }}
data:
  envoy.yaml: |
{{ .Values.envoy.bootstrap | indent 4 }}
{{- end }}
